plugin : 
  has_options: true
  #icon: res_msword.png
  tools:
     - name: Imavia 
       is_displayable_in_workspace: true
<<<<<<< .mine
       is_displayable_in_desktop: true=======
       is_displayable_in_desktop: true
       
>>>>>>> .r42
