services: 
  imavia.listener.FacetProfileListener: 
    class: Imavia\FacetProfileBundle\Listener\FacetProfileListener
    calls: 
      - [setContainer, ["@service_container"]]
    tags:
       - { name: kernel.event_listener, event: open_tool_desktop_Imavia, method: onStartUp }
      